# Generated by Django 4.2.2 on 2023-06-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_registration', '0003_report_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institution_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
