# Generated by Django 4.2.2 on 2023-06-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_registration', '0004_remove_report_reported_user_remove_report_reporter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
