# Generated by Django 4.2.2 on 2023-06-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_registration', '0005_remove_customuser_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='state',
            new_name='district',
        ),
    ]
