# Generated by Django 4.2.2 on 2023-06-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_registration', '0006_rename_state_customuser_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_contact',
            field=models.BooleanField(default=False),
        ),
    ]
