# Generated by Django 4.2.4 on 2023-08-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_registration', '0009_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined']},
        ),
    ]
