# Generated by Django 4.2.4 on 2023-09-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_registration', '0010_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('parttime', 'Part-Time'), ('fulltime', 'Full-Time'), ('admin', 'Admin'), ('tutor', 'Tutor')], default='tutor', max_length=20),
        ),
    ]
