# Generated by Django 4.2.4 on 2023-12-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_registration', '0011_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('parttime', 'Part-Time'), ('fulltime', 'Full-Time'), ('admin', 'Admin'), ('tutor', 'Tutor'), ('employ', 'Employ')], default='tutor', max_length=20),
        ),
    ]
